library(MorbiditySpainR)

context("Morbidity packages test")

#GetMorbiData
test_that("Todas las funciones",{
  expect_equal(nrow(data_test),9188986)
  expect_equal(as.numeric(data_test[1000,"edad"]),60)
  result1 <- data_test %>% FilterProvincia(provincia = 28)
  expect_equal(nrow(result1),1335480)
  expect_equal(as.numeric(result1[1000,"edad"]),41)
  result2 <- result1 %>% FilterEmergency()
  expect_equal(nrow(result2),725128)
  expect_equal(as.numeric(result2[1000,"edad"]),86)
  result3 <-  suppressMessages(AddDiagnosis1(result2))
  expect_equal(as.numeric(result3[1000,"diag1"]),2)
  result4 <- suppressMessages(AddDiagnosis2(result2))
  expect_equal(as.numeric(result4[1000,"diag2"]),18)
  result5 <- suppressMessages(FilterDiagnosis1(result4,diagnosis_id = 2))
  expect_equal(nrow(result5),33507)
  expect_equal(as.numeric(result5[1000,"diag2"]),19)
  result6 <- result5 %>% FilterDiagnosis2(diagnosis_id = 19)
  expect_equal(nrow(result6),4898)
  expect_equal(as.numeric(result6[1000,"edad"]),66)
  result7 <- suppressMessages(AddDiagnosis3(result6))
  expect_equal(result7[1000,]$diag3," Bronchus and lung, unspecified")
  reduce1 <- suppressMessages(ReduceData(data = data_test,provincia = TRUE,date="year"))
  expect_equal(reduce1[100,]$total,257)
  reduce2 <- suppressMessages(ReduceData(data = result5,provincia = TRUE,date = "day"))
  expect_equal(reduce2[500,]$total,31)
  reduce3 <- suppressMessages(SetPrevalence(data = reduce1))
  expect_equal(reduce3[100,]$total.prev,7259.832)
})